services:
  postgres:
    image: postgres:16
    container_name: challenge-postgres
    restart: always
    environment:
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: challenge
      POSTGRES_DB: challenge_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: